### ISSUE TITLE
[FEATURE] Add Delete Poll functionality on the Dashboard.

### ISSUE THREAD

**Issue by debsouryadatta** [agamjotsingh18/pollitup#149]
## Expected Behavior
There will be a delete poll option on the dashboard along with the polls

## Current Behavior
The polls on the dashboard don't have any options to be deleted.

I want to work on this issue, Please label and assign it to me.

**Comment by debsouryadatta** [comment]
Hello @Arnabdaz  , since the version of react-router-dom is V5 so I can't use useNavigate hook to refresh the page without reloading after the delete functionality works, so shall I implement location.reload on the same?

**Comment by Arnabdaz** [comment]
@debsouryadatta  In react-router-dom v5, instead of useNavigate, we typically use the useHistory hook. After performing a delete operation, you can use the history.push() or history.replace() methods to redirect the user to a new location.
This will not cause the entire page to reload, but it will cause the relevant components to re-render, which should be sufficient to reflect the changes caused by the delete operation.
